- hosts: localhost
  gather_facts: false

  roles:
    - role: set_vars  # load variables

  tasks:
    - name: Include only the single task from print_var role
      include_role:
        name: print_var
        tasks_from: print_my_var
